# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_makan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from makanan import Makanan
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_menu2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu2.setEnabled(True)
        self.btn_menu2.setGeometry(QtCore.QRect(10, 0, 571, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.btn_menu2.sizePolicy().hasHeightForWidth())
        self.btn_menu2.setSizePolicy(sizePolicy)
        self.btn_menu2.setStyleSheet("QPushButton {\n"
"    background-color: #0078D4;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005fa3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003f6b;\n"
"}\n"
"")
        self.btn_menu2.setObjectName("btn_menu2")
        self.btn_menu2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu2_3.setEnabled(True)
        self.btn_menu2_3.setGeometry(QtCore.QRect(10, 90, 571, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.btn_menu2_3.sizePolicy().hasHeightForWidth())
        self.btn_menu2_3.setSizePolicy(sizePolicy)
        self.btn_menu2_3.setStyleSheet("QPushButton {\n"
"    background-color: #0078D4;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005fa3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003f6b;\n"
"}\n"
"")
        self.btn_menu2_3.setText("")
        self.btn_menu2_3.setObjectName("btn_menu2_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 100, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 220, 230, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_save = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_save.setStyleSheet("QPushButton {\n"
"    background-color: #005fa3;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005fa3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003f6b;\n"
"}\n"
"")
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_back = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_back.setStyleSheet("QPushButton {\n"
"    background-color: #005fa3;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005fa3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003f6b;\n"
"}\n"
"")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 140, 211, 111))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget_3)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_6.setStyleSheet("QLabel {font-size:10px; color:black;}")
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_id_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_id_2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4;\n"
"}")
        self.lineEdit_id_2.setObjectName("lineEdit_id_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_id_2)
        self.btn_search_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_search_2.setStyleSheet("QPushButton {\n"
"    background-color: #0078D4;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005fa3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003f6b;\n"
"}\n"
"")
        self.btn_search_2.setObjectName("btn_search_2")
        self.horizontalLayout_3.addWidget(self.btn_search_2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setStyleSheet("QLabel {font-size:10px; color:black;}")
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_nama_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_nama_2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4;\n"
"}")
        self.lineEdit_nama_2.setObjectName("lineEdit_nama_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nama_2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setStyleSheet("QLabel {font-size:10px; color:black;}")
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_harga_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_harga_2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4;\n"
"}")
        self.lineEdit_harga_2.setObjectName("lineEdit_harga_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_harga_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(300, 140, 241, 66))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setStyleSheet("QLabel {font-size:10px; color:black;}")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        self.label.setStyleSheet("QLabel {font-size:10px; color:black;}")
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_kategori = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_kategori.setStyleSheet("QComboBox {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    color: black;\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"    color: black;              \n"
"    background: white;        \n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #0078D4;\n"
"}")
        self.comboBox_kategori.setObjectName("comboBox_kategori")
        self.comboBox_kategori.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_kategori)
        self.lineEdit_stok = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_stok.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4;\n"
"}")
        self.lineEdit_stok.setObjectName("lineEdit_stok")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_stok)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_search_2.clicked.connect(self.CariData)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_menu2.setText(_translate("MainWindow", "Selamat Datang Restoran Kami"))
        self.lineEdit.setText(_translate("MainWindow", "MAKAN"))
        self.btn_save.setText(_translate("MainWindow", "Update"))
        self.btn_back.setText(_translate("MainWindow", "Back"))
        self.label_6.setText(_translate("MainWindow", "ID"))
        self.btn_search_2.setText(_translate("MainWindow", "Cari"))
        self.label_7.setText(_translate("MainWindow", "Makan"))
        self.label_8.setText(_translate("MainWindow", "Harga"))
        self.label_4.setText(_translate("MainWindow", "Stok"))
        self.label.setText(_translate("MainWindow", "Kategori"))
        self.comboBox_kategori.setItemText(0, _translate("MainWindow", "dessert"))

    def CariData(self):
        id_menu = self.lineEdit.text()
        data = Makanan.select_by_id([id_menu])

        if not data:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox().Warning)
            msg.setWindowTitle("Data Tidak Ditemukan")
            msg.setText(f"Data dengan ID '{id}' tidak ditemukan!")
            msg.exec_()

            self.lineEdit.clear()
            self.lineEdit_nama_2.clear()
            self.lineEdit_harga_2.clear()
            self.lineEdit_stok.clear()
            self.comboBox_kategori.setCurrentIndex(0)
            return

        nama = data[1]
        harga = data[2]
        stok = data[3]
        kategori = data[4]

        self.lineEdit_nama_2.setText(str(nama))
        self.lineEdit_harga_2.setText(str(harga))
        self.lineEdit_stok.setText(str(stok))
        self.comboBox_kategori.setCurrentText(str(kategori))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
