# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_riwayat_kasir.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from transkasi import Transaksi
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 466)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_name_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_name_widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.icon_name_widget.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 171, 146);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: black;\n"
"    background-color: #FAF3E1;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #FF6D1F;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.icon_name_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border-radius: 20px;\n"
"    background-image: url(:/yourpic.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/images/logo-rounded.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.icon_name_widget)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #FAF3E1;")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.icon_name_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #222222;")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.icon_name_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.btn_dashboard_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dashboard_expanded.setFont(font)
        self.btn_dashboard_expanded.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btn_dashboard_expanded.setIcon(icon)
        self.btn_dashboard_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_dashboard_expanded.setCheckable(True)
        self.btn_dashboard_expanded.setChecked(False)
        self.btn_dashboard_expanded.setAutoExclusive(True)
        self.btn_dashboard_expanded.setObjectName("btn_dashboard_expanded")
        self.verticalLayout_2.addWidget(self.btn_dashboard_expanded)
        self.btn_transaksi_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_transaksi_expanded.setFont(font)
        self.btn_transaksi_expanded.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/mage--shopping-cart-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/image/images/mage--shopping-cart-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_transaksi_expanded.setIcon(icon1)
        self.btn_transaksi_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_transaksi_expanded.setCheckable(True)
        self.btn_transaksi_expanded.setChecked(False)
        self.btn_transaksi_expanded.setAutoExclusive(True)
        self.btn_transaksi_expanded.setObjectName("btn_transaksi_expanded")
        self.verticalLayout_2.addWidget(self.btn_transaksi_expanded)
        self.btn_menu_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_expanded.setFont(font)
        self.btn_menu_expanded.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/mage--clipboard-2-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/image/images/mage--clipboard-2-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_menu_expanded.setIcon(icon2)
        self.btn_menu_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_expanded.setCheckable(True)
        self.btn_menu_expanded.setAutoExclusive(True)
        self.btn_menu_expanded.setObjectName("btn_menu_expanded")
        self.verticalLayout_2.addWidget(self.btn_menu_expanded)
        self.btn_riwayat_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_riwayat_expanded.setFont(font)
        self.btn_riwayat_expanded.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/mage--book-text-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/image/images/mage--book-text-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_riwayat_expanded.setIcon(icon3)
        self.btn_riwayat_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_riwayat_expanded.setCheckable(True)
        self.btn_riwayat_expanded.setChecked(True)
        self.btn_riwayat_expanded.setAutoExclusive(True)
        self.btn_riwayat_expanded.setObjectName("btn_riwayat_expanded")
        self.verticalLayout_2.addWidget(self.btn_riwayat_expanded)
        spacerItem = QtWidgets.QSpacerItem(40, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_logout_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout_expanded.setFont(font)
        self.btn_logout_expanded.setStyleSheet("QPushButton {\n"
"    border-radius: 12px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/mage--shut-down-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/image/images/mage--shut-down-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_logout_expanded.setIcon(icon4)
        self.btn_logout_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_logout_expanded.setObjectName("btn_logout_expanded")
        self.verticalLayout_2.addWidget(self.btn_logout_expanded)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_menu = QtWidgets.QWidget(self.centralwidget)
        self.main_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_menu.setObjectName("main_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.main_menu)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setStyleSheet("background-color: rgb(250, 243, 225);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_expand = QtWidgets.QPushButton(self.widget)
        self.btn_expand.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: black;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F5E7C6;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #222222;\n"
"}")
        self.btn_expand.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/images/mage--dash-menu-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/image/images/mage--double-arrow-left-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_expand.setIcon(icon5)
        self.btn_expand.setIconSize(QtCore.QSize(20, 20))
        self.btn_expand.setCheckable(True)
        self.btn_expand.setObjectName("btn_expand")
        self.horizontalLayout.addWidget(self.btn_expand)
        spacerItem1 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.main_menu)
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(250, 243, 225);\n"
"}\n"
"\n"
"QLabel {\n"
"    color:black;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border-radius:  5px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 3px 6px;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    width: 20px;\n"
"    border: none;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #F5E7C6;\n"
"    border-radius: 12px;\n"
"    gridline-color: #F5E7C6;\n"
"    selection-background-color: rgb(181, 171, 146);\n"
"    selection-color: #222222;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F5E7C6;\n"
"    color: #222222;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-right: 1px solid #FAF3E1;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: #F5E7C6;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: rgba(181, 171, 146, 90%);\n"
"    color: #222222;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(181, 171, 146);\n"
"    color: #222222;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 12px;\n"
"    margin: 6px 0 6px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #F5E7C6;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(181, 171, 146);\n"
"}\n"
"\n"
"QScrollBar::add-line,\n"
"QScrollBar::sub-line {\n"
"    height: 0;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #F5E7C6;\n"
"    border: none;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:black;")
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_11.addWidget(self.comboBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.widget_2)
        self.dateEdit_3.setMinimumSize(QtCore.QSize(100, 30))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.horizontalLayout_11.addWidget(self.dateEdit_3)
        self.dateEdit = QtWidgets.QDateEdit(self.widget_2)
        self.dateEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_11.addWidget(self.dateEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_8.addWidget(self.tableWidget)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_9.addWidget(self.lineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.gridLayout.addWidget(self.main_menu, 0, 2, 1, 1)
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setMaximumSize(QtCore.QSize(75, 16777215))
        self.icon_only_widget.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 171, 146);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: black;\n"
"    background-color: #FAF3E1;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #FF6D1F;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.icon_only_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(40, 40))
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border-radius: 20px;\n"
"    background-image: url(:/yourpic.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/image/images/logo-rounded.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.icon_only_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.btn_dashboard_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dashboard_icon.setFont(font)
        self.btn_dashboard_icon.setStyleSheet("")
        self.btn_dashboard_icon.setText("")
        self.btn_dashboard_icon.setIcon(icon)
        self.btn_dashboard_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_dashboard_icon.setCheckable(True)
        self.btn_dashboard_icon.setChecked(False)
        self.btn_dashboard_icon.setAutoExclusive(True)
        self.btn_dashboard_icon.setObjectName("btn_dashboard_icon")
        self.verticalLayout_7.addWidget(self.btn_dashboard_icon)
        self.btn_transaksi_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_transaksi_icon.setFont(font)
        self.btn_transaksi_icon.setStyleSheet("")
        self.btn_transaksi_icon.setText("")
        self.btn_transaksi_icon.setIcon(icon1)
        self.btn_transaksi_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_transaksi_icon.setCheckable(True)
        self.btn_transaksi_icon.setChecked(False)
        self.btn_transaksi_icon.setAutoExclusive(True)
        self.btn_transaksi_icon.setObjectName("btn_transaksi_icon")
        self.verticalLayout_7.addWidget(self.btn_transaksi_icon)
        self.btn_menu_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_icon.setFont(font)
        self.btn_menu_icon.setStyleSheet("")
        self.btn_menu_icon.setText("")
        self.btn_menu_icon.setIcon(icon2)
        self.btn_menu_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_icon.setCheckable(True)
        self.btn_menu_icon.setAutoExclusive(True)
        self.btn_menu_icon.setObjectName("btn_menu_icon")
        self.verticalLayout_7.addWidget(self.btn_menu_icon)
        self.btn_riwayat_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_riwayat_icon.setFont(font)
        self.btn_riwayat_icon.setStyleSheet("")
        self.btn_riwayat_icon.setText("")
        self.btn_riwayat_icon.setIcon(icon3)
        self.btn_riwayat_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_riwayat_icon.setCheckable(True)
        self.btn_riwayat_icon.setChecked(True)
        self.btn_riwayat_icon.setAutoExclusive(True)
        self.btn_riwayat_icon.setObjectName("btn_riwayat_icon")
        self.verticalLayout_7.addWidget(self.btn_riwayat_icon)
        spacerItem6 = QtWidgets.QSpacerItem(40, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.btn_logout_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout_icon.setFont(font)
        self.btn_logout_icon.setStyleSheet("QPushButton {\n"
"    border-radius: 12px;\n"
"}")
        self.btn_logout_icon.setText("")
        self.btn_logout_icon.setIcon(icon4)
        self.btn_logout_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_logout_icon.setObjectName("btn_logout_icon")
        self.verticalLayout_7.addWidget(self.btn_logout_icon)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.btn_dashboard_expanded.clicked.connect(self.goto_dashboard)
        self.btn_transaksi_expanded.clicked.connect(self.goto_trx)
        self.btn_menu_expanded.clicked.connect(self.goto_tampilmenu)    
        self.btn_logout_expanded.clicked.connect(self.goto_logout)
        self.btn_dashboard_icon.clicked.connect(self.goto_dashboard)
        self.btn_transaksi_icon.clicked.connect(self.goto_trx)
        self.btn_menu_icon.clicked.connect(self.goto_tampilmenu)
        self.btn_logout_icon.clicked.connect(self.goto_logout)

        self.retranslateUi(MainWindow)
        self.btn_expand.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.btn_expand.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.btn_logout_expanded.clicked.connect(MainWindow.close) # type: ignore
        self.btn_riwayat_expanded.toggled['bool'].connect(self.btn_riwayat_icon.setChecked) # type: ignore
        self.btn_menu_expanded.toggled['bool'].connect(self.btn_menu_icon.setChecked) # type: ignore
        self.btn_riwayat_icon.toggled['bool'].connect(self.btn_riwayat_expanded.setChecked) # type: ignore
        self.btn_menu_icon.toggled['bool'].connect(self.btn_menu_expanded.setChecked) # type: ignore
        self.btn_logout_icon.clicked.connect(MainWindow.close) # type: ignore
        self.btn_dashboard_icon.toggled['bool'].connect(self.btn_dashboard_expanded.setChecked) # type: ignore
        self.btn_dashboard_expanded.toggled['bool'].connect(self.btn_dashboard_icon.setChecked) # type: ignore
        self.btn_transaksi_expanded.toggled['bool'].connect(self.btn_transaksi_icon.setChecked) # type: ignore
        self.btn_transaksi_icon.toggled['bool'].connect(self.btn_transaksi_expanded.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.loggedInUsername = "ILHAM" # <-- Ganti dengan cara Anda mendapatkan username dari Form Login
        
        # Inisialisasi widget
        self.tableWidget_riwayat = self.tableWidget # Asumsi nama tabel adalah tableWidget
        self.lineEdit_total_riwayat = self.lineEdit# Asumsi field total adalah lineEdit_total
        
        # Set field Kasir dengan username yang login (dan disable jika hanya boleh lihat transaksi sendiri)
        self.comboBox_2.clear()
        self.comboBox_2.addItem(self.loggedInUsername)
        self.comboBox_2.setEnabled(False) 
        
        # Set format date time edits
        self.dateEdit_3.setDisplayFormat("yyyy-MM-dd")
        self.dateEdit.setDisplayFormat("yyyy-MM-dd")
        
        # Koneksi Tombol Cari (Anda harus menambahkan QPushButton di UI Anda)
        self.btn_cari_riwayat = QtWidgets.QPushButton(self.centralwidget) # ASUMSI WIDGET BARU
        self.btn_cari_riwayat.setText("Tampilkan Riwayat")
        self.pushButton.clicked.connect(self.display_riwayat)
        
        # ... (Hubungkan widget baru ke layout yang sesuai) ...

        # Panggil sekali di awal untuk menampilkan riwayat hari ini
        self.set_default_date_range()
        self.display_riwayat()

    #ganti halaman    
    def goto_dashboard(self):
        from kasir_dashboard import Ui_MainWindow as KasirDashboard
        self.window = QtWidgets.QMainWindow()
        self.ui = KasirDashboard()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def goto_trx(self):
        from form_proses_transaksi2 import Ui_MainWindow as ProsesTransaksi
        self.window = QtWidgets.QMainWindow()
        self.ui = ProsesTransaksi()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def goto_tampilmenu(self):
        from tampil_menu import Ui_MainWindow as MenuKasir
        self.window = QtWidgets.QMainWindow()
        self.ui = MenuKasir()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()
        
    def goto_logout(self):
        from form_login import Ui_MainWindow as formlogin
        self.window = QtWidgets.QMainWindow()
        self.ui = formlogin()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "NIBA"))
        self.label_5.setText(_translate("MainWindow", "RESTO"))
        self.btn_dashboard_expanded.setText(_translate("MainWindow", "Dashboard"))
        self.btn_transaksi_expanded.setText(_translate("MainWindow", "Transaksi"))
        self.btn_menu_expanded.setText(_translate("MainWindow", "Menu"))
        self.btn_riwayat_expanded.setText(_translate("MainWindow", "Riwayat"))
        self.btn_logout_expanded.setText(_translate("MainWindow", "Logout"))
        self.label_7.setText(_translate("MainWindow", "Form Riwayat"))
        self.label_12.setText(_translate("MainWindow", "Kasir"))
        self.pushButton.setText(_translate("MainWindow", "Cari"))
        self.label_10.setText(_translate("MainWindow", "Total Pendapatan (Rp) :"))

    def set_default_date_range(self):
        """Mengatur rentang tanggal default (misalnya, 7 hari terakhir atau hari ini)."""
        today = QtCore.QDate.currentDate()
        last_week = today.addDays(-7) 
        self.dateEdit_3.setDate(last_week) 
        self.dateEdit.setDate(today)

    def display_riwayat(self):
        # Ambil rentang tanggal dari QDateEdit dan format ke string SQL (YYYY-MM-DD)
        tgl_awal = self.dateEdit_3.date().toString("yyyy-MM-dd")
        # Tambahkan 1 hari untuk tanggal akhir agar rentang mencakup seluruh hari terakhir
        tgl_akhir_obj = self.dateEdit.date().addDays(1)
        tgl_akhir = tgl_akhir_obj.toString("yyyy-MM-dd")
        
        kasir = self.loggedInUsername # Ambil username kasir yang sedang login
        
        # Instance dummy Transaksi
        tr_instance = Transaksi() 
        
        try:
                # 1. Ambil Data Riwayat (Nota per Nota)
                riwayat_data = tr_instance.get_riwayat_by_kasir(kasir, tgl_awal, tgl_akhir)
                
                # 2. Hitung Total Keseluruhan
                grand_total = tr_instance.calculate_total_riwayat(kasir, tgl_awal, tgl_akhir)
                
                # 3. Isi Tabel
                self.fill_riwayat_table(riwayat_data)
                
                # 4. Tampilkan Total
                self.lineEdit_total_riwayat.setText(f"{grand_total:,.0f}")
                
        except Exception as e:
                QtWidgets.QMessageBox.critical(self.centralwidget, "DB Error", f"Gagal memuat riwayat: {e}")


    def fill_riwayat_table(self, data):
        """Mengisi QTableWidget dengan data riwayat transaksi (nota per nota)."""
        table = self.tableWidget_riwayat
        table.setRowCount(0)
        
        headers = [
                "ID Item", "Kode Transaksi", "Nama Menu", 
                "Kasir", "Qty", "Subtotal (Rp)", "Tanggal/Waktu"
        ]
        table.setColumnCount(len(headers))
        table.setHorizontalHeaderLabels(headers)
        table.setRowCount(len(data))
        
        for row_num, row_data in enumerate(data):
                # row_data: (id_transaksi, kode_transaksi, nama_menu, username_kasir, qty, harga_total, tanggal)
                
                # Ekstrak data untuk kemudahan (opsional, tapi disarankan)
                id_transaksi, kode_transaksi, nama_menu, username_kasir, qty, harga_total, tanggal_dt = row_data
                
                # Kolom 0: ID Item
                table.setItem(row_num, 0, QtWidgets.QTableWidgetItem(str(id_transaksi)))

                # Kolom 1: Kode Transaksi
                table.setItem(row_num, 1, QtWidgets.QTableWidgetItem(str(kode_transaksi)))

                # Kolom 2: Nama Menu
                table.setItem(row_num, 2, QtWidgets.QTableWidgetItem(nama_menu))
                
                # Kolom 3: Kasir
                table.setItem(row_num, 3, QtWidgets.QTableWidgetItem(username_kasir))
                
                # Kolom 4: Qty
                table.setItem(row_num, 4, QtWidgets.QTableWidgetItem(str(qty)))
                
                # Kolom 5: Subtotal (Harga Total Item) - Format Rupiah
                table.setItem(row_num, 5, QtWidgets.QTableWidgetItem(f"{harga_total:,.0f}"))
                
                # Kolom 6: Tanggal/Waktu (Format Datetime)
                # Mengubah objek datetime dari DB menjadi string format YYYY-MM-DD HH:MM:SS
                if tanggal_dt:
                # Asumsi tanggal_dt adalah objek datetime/timestamp
                        tanggal_str = tanggal_dt.strftime("%Y-%m-%d %H:%M:%S") 
                else:
                        tanggal_str = ""
                
                table.setItem(row_num, 6, QtWidgets.QTableWidgetItem(tanggal_str))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
