# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kasir_dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from user import User
from menu import Menu
from transkasi import Transaksi 



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 474)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setMaximumSize(QtCore.QSize(75, 16777215))
        self.icon_only_widget.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 171, 146);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: black;\n"
"    background-color: #FAF3E1;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #FF6D1F;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.icon_only_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(40, 40))
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border-radius: 20px;\n"
"    background-image: url(:/yourpic.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/image/images/logo-rounded.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.icon_only_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.btn_dashboard_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dashboard_icon.setFont(font)
        self.btn_dashboard_icon.setStyleSheet("")
        self.btn_dashboard_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btn_dashboard_icon.setIcon(icon)
        self.btn_dashboard_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_dashboard_icon.setCheckable(True)
        self.btn_dashboard_icon.setChecked(True)
        self.btn_dashboard_icon.setAutoExclusive(True)
        self.btn_dashboard_icon.setObjectName("btn_dashboard_icon")
        self.verticalLayout_7.addWidget(self.btn_dashboard_icon)
        self.btn_transaksi_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_transaksi_icon.setFont(font)
        self.btn_transaksi_icon.setStyleSheet("")
        self.btn_transaksi_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/mage--shopping-cart-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/image/images/mage--shopping-cart-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_transaksi_icon.setIcon(icon1)
        self.btn_transaksi_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_transaksi_icon.setCheckable(True)
        self.btn_transaksi_icon.setChecked(False)
        self.btn_transaksi_icon.setAutoExclusive(True)
        self.btn_transaksi_icon.setObjectName("btn_transaksi_icon")
        self.verticalLayout_7.addWidget(self.btn_transaksi_icon)
        self.btn_menu_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_icon.setFont(font)
        self.btn_menu_icon.setStyleSheet("")
        self.btn_menu_icon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/mage--clipboard-2-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/image/images/mage--clipboard-2-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_menu_icon.setIcon(icon2)
        self.btn_menu_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_icon.setCheckable(True)
        self.btn_menu_icon.setAutoExclusive(True)
        self.btn_menu_icon.setObjectName("btn_menu_icon")
        self.verticalLayout_7.addWidget(self.btn_menu_icon)
        self.btn_riwayat_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_riwayat_icon.setFont(font)
        self.btn_riwayat_icon.setStyleSheet("")
        self.btn_riwayat_icon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/mage--book-text-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/image/images/mage--book-text-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_riwayat_icon.setIcon(icon3)
        self.btn_riwayat_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_riwayat_icon.setCheckable(True)
        self.btn_riwayat_icon.setChecked(False)
        self.btn_riwayat_icon.setAutoExclusive(True)
        self.btn_riwayat_icon.setObjectName("btn_riwayat_icon")
        self.verticalLayout_7.addWidget(self.btn_riwayat_icon)
        spacerItem = QtWidgets.QSpacerItem(40, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.btn_logout_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout_icon.setFont(font)
        self.btn_logout_icon.setStyleSheet("QPushButton {\n"
"    border-radius: 12px;\n"
"}")
        self.btn_logout_icon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/mage--shut-down-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/image/images/mage--shut-down-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_logout_icon.setIcon(icon4)
        self.btn_logout_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_logout_icon.setObjectName("btn_logout_icon")
        self.verticalLayout_7.addWidget(self.btn_logout_icon)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_name_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_name_widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.icon_name_widget.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 171, 146);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: black;\n"
"    background-color: #FAF3E1;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #FF6D1F;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.icon_name_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border-radius: 20px;\n"
"    background-image: url(:/yourpic.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/images/logo-rounded.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.icon_name_widget)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #FAF3E1;")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.icon_name_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #222222;")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.icon_name_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.btn_dashboard_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dashboard_expanded.setFont(font)
        self.btn_dashboard_expanded.setStyleSheet("")
        self.btn_dashboard_expanded.setIcon(icon)
        self.btn_dashboard_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_dashboard_expanded.setCheckable(True)
        self.btn_dashboard_expanded.setChecked(True)
        self.btn_dashboard_expanded.setAutoExclusive(True)
        self.btn_dashboard_expanded.setObjectName("btn_dashboard_expanded")
        self.verticalLayout_2.addWidget(self.btn_dashboard_expanded)
        self.btn_transaksi_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_transaksi_expanded.setFont(font)
        self.btn_transaksi_expanded.setStyleSheet("")
        self.btn_transaksi_expanded.setIcon(icon1)
        self.btn_transaksi_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_transaksi_expanded.setCheckable(True)
        self.btn_transaksi_expanded.setChecked(False)
        self.btn_transaksi_expanded.setAutoExclusive(True)
        self.btn_transaksi_expanded.setObjectName("btn_transaksi_expanded")
        self.verticalLayout_2.addWidget(self.btn_transaksi_expanded)
        self.btn_menu_expanded_2 = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_expanded_2.setFont(font)
        self.btn_menu_expanded_2.setStyleSheet("")
        self.btn_menu_expanded_2.setIcon(icon2)
        self.btn_menu_expanded_2.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_expanded_2.setCheckable(True)
        self.btn_menu_expanded_2.setAutoExclusive(True)
        self.btn_menu_expanded_2.setObjectName("btn_menu_expanded_2")
        self.verticalLayout_2.addWidget(self.btn_menu_expanded_2)
        self.btn_riwayat_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_riwayat_expanded.setFont(font)
        self.btn_riwayat_expanded.setStyleSheet("")
        self.btn_riwayat_expanded.setIcon(icon3)
        self.btn_riwayat_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_riwayat_expanded.setCheckable(True)
        self.btn_riwayat_expanded.setChecked(False)
        self.btn_riwayat_expanded.setAutoExclusive(True)
        self.btn_riwayat_expanded.setObjectName("btn_riwayat_expanded")
        self.verticalLayout_2.addWidget(self.btn_riwayat_expanded)
        spacerItem1 = QtWidgets.QSpacerItem(40, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.btn_logout_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout_expanded.setFont(font)
        self.btn_logout_expanded.setStyleSheet("QPushButton {\n"
"    border-radius: 12px;\n"
"}")
        self.btn_logout_expanded.setIcon(icon4)
        self.btn_logout_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_logout_expanded.setObjectName("btn_logout_expanded")
        self.verticalLayout_2.addWidget(self.btn_logout_expanded)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_menu = QtWidgets.QWidget(self.centralwidget)
        self.main_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_menu.setObjectName("main_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.main_menu)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(250, 243, 225);\n"
"}\n"
"\n"
"QDateTimeEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 3px 6px;\n"
"}\n"
"\n"
"QDateTimeEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    width: 20px;\n"
"    border: none;\n"
"}\n"
"\n"
"QDateTimeEdit::down-arrow {\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_expand = QtWidgets.QPushButton(self.widget)
        self.btn_expand.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: black;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F5E7C6;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #222222;\n"
"}")
        self.btn_expand.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/images/mage--dash-menu-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/image/images/mage--double-arrow-left-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_expand.setIcon(icon5)
        self.btn_expand.setIconSize(QtCore.QSize(20, 20))
        self.btn_expand.setCheckable(True)
        self.btn_expand.setObjectName("btn_expand")
        self.horizontalLayout.addWidget(self.btn_expand)
        spacerItem2 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.main_menu)
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(250, 243, 225);\n"
"}\n"
"\n"
"QLabel {\n"
"    color:black;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border-radius:  5px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #F5E7C6;\n"
"    border-radius: 12px;\n"
"    gridline-color: #F5E7C6;\n"
"    selection-background-color: rgb(181, 171, 146);\n"
"    selection-color: #222222;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F5E7C6;\n"
"    color: #222222;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-right: 1px solid #FAF3E1;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: #F5E7C6;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: rgba(181, 171, 146, 90%);\n"
"    color: #222222;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(181, 171, 146);\n"
"    color: #222222;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 12px;\n"
"    margin: 6px 0 6px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #F5E7C6;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(181, 171, 146);\n"
"}\n"
"\n"
"QScrollBar::add-line,\n"
"QScrollBar::sub-line {\n"
"    height: 0;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #F5E7C6;\n"
"    border: none;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setMaximumSize(QtCore.QSize(50, 50))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/image/images/streamline-plump-color--burger-flat.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.widget_5)
        self.label_16.setMaximumSize(QtCore.QSize(50, 50))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/image/images/streamline-plump-color--money-cash-bill-1.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_17 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17, 0, QtCore.Qt.AlignHCenter)
        self.label_18 = QtWidgets.QLabel(self.widget_5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_14.addWidget(self.label_18, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setMaximumSize(QtCore.QSize(50, 50))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/image/images/icon-park--transaction-order.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.widget_6)
        self.label_19.setMaximumSize(QtCore.QSize(50, 50))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/image/images/fluent-color--people-48.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.label_20, 0, QtCore.Qt.AlignHCenter)
        self.label_21 = QtWidgets.QLabel(self.widget_6)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_13.addWidget(self.label_21, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.horizontalLayout_5.addWidget(self.widget_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 139, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.gridLayout.addWidget(self.main_menu, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.jumlah_menu()
        self.jumlah_transaksi()
        self.omset()
        self.jumlah_user()
        self.btn_menu_expanded_2.clicked.connect(self.goto_menu)
        self.btn_transaksi_expanded.clicked.connect(self.goto_trx)
        self.btn_riwayat_expanded.clicked.connect(self.goto_riwayatkasir)
        self.btn_logout_expanded.clicked.connect(self.goto_logout)
        self.btn_menu_icon.clicked.connect(self.goto_menu)
        self.btn_transaksi_icon.clicked.connect(self.goto_trx)
        self.btn_riwayat_icon.clicked.connect(self.goto_riwayatkasir)
        self.btn_logout_icon.clicked.connect(self.goto_logout)


        self.retranslateUi(MainWindow)
        self.btn_expand.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.btn_expand.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        #self.btn_logout_expanded.clicked.connect(MainWindow.close) # type: ignore
        self.btn_transaksi_expanded.toggled['bool'].connect(self.btn_transaksi_icon.setChecked) # type: ignore
        self.btn_transaksi_icon.toggled['bool'].connect(self.btn_transaksi_expanded.setChecked) # type: ignore
        #self.btn_logout_icon.clicked.connect(MainWindow.close) # type: ignore
        self.btn_dashboard_expanded.toggled['bool'].connect(self.btn_dashboard_icon.setChecked) # type: ignore
        self.btn_dashboard_icon.toggled['bool'].connect(self.btn_dashboard_expanded.setChecked) # type: ignore
        self.btn_menu_expanded_2.toggled['bool'].connect(self.btn_menu_icon.setChecked) # type: ignore
        self.btn_menu_icon.toggled['bool'].connect(self.btn_menu_expanded_2.setChecked) # type: ignore
        self.btn_riwayat_expanded.toggled['bool'].connect(self.btn_riwayat_icon.setChecked) # type: ignore
        self.btn_riwayat_icon.toggled['bool'].connect(self.btn_riwayat_expanded.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#ganti halaman
    def goto_menu(self):
        from tampil_menu import Ui_MainWindow as MenuKasir
        self.window = QtWidgets.QMainWindow()
        self.ui = MenuKasir()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()
    def goto_trx(self):
        from form_proses_transaksi2 import Ui_MainWindow as ProsesTransaksi
        self.window = QtWidgets.QMainWindow()
        self.ui = ProsesTransaksi()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()
    def goto_riwayatkasir(self):
        from form_riwayat_kasir2 import Ui_MainWindow as RiwayatKasir
        self.window = QtWidgets.QMainWindow()
        self.ui = RiwayatKasir()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()
    def goto_logout(self):
        from form_login import Ui_MainWindow as formlogin
        self.window = QtWidgets.QMainWindow()
        self.ui = formlogin()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def jumlah_menu(self):
        jmlmenu = Menu.jumlah_menu(self)
        self.label_11.setText(str(jmlmenu))
    def jumlah_transaksi(self):
        jmltrx = Transaksi.jumlah_transaksi(self)
        self.label_14.setText(str(jmltrx))
    def omset(self):
        omset_perbulan = Transaksi.omset_bulan_ini(self)
        self.label_17.setText(str(omset_perbulan))
    def jumlah_user(self):
        jmluser = User.jumlah_user(self)
        self.label_20.setText(str(jmluser))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "NIBA"))
        self.label_5.setText(_translate("MainWindow", "RESTO"))
        self.btn_dashboard_expanded.setText(_translate("MainWindow", "Dashboard"))
        self.btn_transaksi_expanded.setText(_translate("MainWindow", "Transaksi"))
        self.btn_menu_expanded_2.setText(_translate("MainWindow", "Menu"))
        self.btn_riwayat_expanded.setText(_translate("MainWindow", "Riwayat"))
        self.btn_logout_expanded.setText(_translate("MainWindow", "Logout"))
        self.label.setText(_translate("MainWindow", "Dashboard"))
        self.label_6.setText(_translate("MainWindow", "Halo, Kasir"))
        self.label_8.setText(_translate("MainWindow", "Jumlah Menu"))
        self.label_18.setText(_translate("MainWindow", "Pendapatan Bulan Ini"))
        self.label_15.setText(_translate("MainWindow", "Jumlah Transaksi"))
        self.label_21.setText(_translate("MainWindow", "Jumlah User"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
