# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from user import User
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 474)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setMaximumSize(QtCore.QSize(75, 16777215))
        self.icon_only_widget.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 171, 146);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: black;\n"
"    background-color: #FAF3E1;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #FF6D1F;\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.icon_only_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(40, 40))
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border-radius: 20px;\n"
"    background-image: url(:/yourpic.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/image/images/logo-rounded.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.icon_only_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.btn_dashboard_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dashboard_icon.setFont(font)
        self.btn_dashboard_icon.setStyleSheet("")
        self.btn_dashboard_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill-off.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/images/mage--home-fill.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btn_dashboard_icon.setIcon(icon)
        self.btn_dashboard_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_dashboard_icon.setCheckable(True)
        self.btn_dashboard_icon.setChecked(False)
        self.btn_dashboard_icon.setAutoExclusive(True)
        self.btn_dashboard_icon.setObjectName("btn_dashboard_icon")
        self.verticalLayout_7.addWidget(self.btn_dashboard_icon)
        self.btn_user_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_user_icon.setFont(font)
        self.btn_user_icon.setStyleSheet("")
        self.btn_user_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/mage--users-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/image/images/mage--users-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_user_icon.setIcon(icon1)
        self.btn_user_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_user_icon.setCheckable(True)
        self.btn_user_icon.setChecked(True)
        self.btn_user_icon.setAutoExclusive(True)
        self.btn_user_icon.setObjectName("btn_user_icon")
        self.verticalLayout_7.addWidget(self.btn_user_icon)
        self.btn_menu_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_icon.setFont(font)
        self.btn_menu_icon.setStyleSheet("")
        self.btn_menu_icon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/mage--clipboard-2-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/image/images/mage--clipboard-2-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_menu_icon.setIcon(icon2)
        self.btn_menu_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_icon.setCheckable(True)
        self.btn_menu_icon.setAutoExclusive(True)
        self.btn_menu_icon.setObjectName("btn_menu_icon")
        self.verticalLayout_7.addWidget(self.btn_menu_icon)
        spacerItem = QtWidgets.QSpacerItem(40, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.btn_logout_icon = QtWidgets.QPushButton(self.icon_only_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout_icon.setFont(font)
        self.btn_logout_icon.setStyleSheet("QPushButton {\n"
"    border-radius: 12px;\n"
"}")
        self.btn_logout_icon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/mage--shut-down-fill-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/image/images/mage--shut-down-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_logout_icon.setIcon(icon3)
        self.btn_logout_icon.setIconSize(QtCore.QSize(20, 20))
        self.btn_logout_icon.setObjectName("btn_logout_icon")
        self.verticalLayout_7.addWidget(self.btn_logout_icon)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.icon_name_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_name_widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.icon_name_widget.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 171, 146);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: black;\n"
"    background-color: #FAF3E1;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #FF6D1F;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_4.setContentsMargins(9, 9, 0, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.icon_name_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border-radius: 20px;\n"
"    background-image: url(:/yourpic.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/image/images/logo-rounded.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.icon_name_widget)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #FAF3E1;")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.icon_name_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #222222;")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.icon_name_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.btn_dashboard_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dashboard_expanded.setFont(font)
        self.btn_dashboard_expanded.setStyleSheet("")
        self.btn_dashboard_expanded.setIcon(icon)
        self.btn_dashboard_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_dashboard_expanded.setCheckable(True)
        self.btn_dashboard_expanded.setChecked(False)
        self.btn_dashboard_expanded.setAutoExclusive(True)
        self.btn_dashboard_expanded.setObjectName("btn_dashboard_expanded")
        self.verticalLayout_2.addWidget(self.btn_dashboard_expanded)
        self.btn_user_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_user_expanded.setFont(font)
        self.btn_user_expanded.setStyleSheet("")
        self.btn_user_expanded.setIcon(icon1)
        self.btn_user_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_user_expanded.setCheckable(True)
        self.btn_user_expanded.setChecked(True)
        self.btn_user_expanded.setAutoExclusive(True)
        self.btn_user_expanded.setObjectName("btn_user_expanded")
        self.verticalLayout_2.addWidget(self.btn_user_expanded)
        self.btn_menu_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_expanded.setFont(font)
        self.btn_menu_expanded.setStyleSheet("")
        self.btn_menu_expanded.setIcon(icon2)
        self.btn_menu_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_menu_expanded.setCheckable(True)
        self.btn_menu_expanded.setAutoExclusive(True)
        self.btn_menu_expanded.setObjectName("btn_menu_expanded")
        self.verticalLayout_2.addWidget(self.btn_menu_expanded)
        spacerItem1 = QtWidgets.QSpacerItem(40, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.btn_logout_expanded = QtWidgets.QPushButton(self.icon_name_widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout_expanded.setFont(font)
        self.btn_logout_expanded.setStyleSheet("QPushButton {\n"
"    border-radius: 12px;\n"
"}")
        self.btn_logout_expanded.setIcon(icon3)
        self.btn_logout_expanded.setIconSize(QtCore.QSize(20, 20))
        self.btn_logout_expanded.setObjectName("btn_logout_expanded")
        self.verticalLayout_2.addWidget(self.btn_logout_expanded)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_menu = QtWidgets.QWidget(self.centralwidget)
        self.main_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_menu.setObjectName("main_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.main_menu)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setStyleSheet("background-color: rgb(250, 243, 225);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_expand = QtWidgets.QPushButton(self.widget)
        self.btn_expand.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    color: black;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F5E7C6;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #222222;\n"
"}")
        self.btn_expand.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/mage--dash-menu-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/image/images/mage--double-arrow-left-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_expand.setIcon(icon4)
        self.btn_expand.setIconSize(QtCore.QSize(20, 20))
        self.btn_expand.setCheckable(True)
        self.btn_expand.setObjectName("btn_expand")
        self.horizontalLayout.addWidget(self.btn_expand)
        spacerItem2 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.main_menu)
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(250, 243, 225);\n"
"}\n"
"\n"
"QLabel {\n"
"    color:black;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border-radius:  5px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:black;")
        self.label_19.setScaledContents(False)
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.widget_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(1000, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_22.addWidget(self.lineEdit_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(1000, 30))
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_12.addWidget(self.lineEdit_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(1000, 30))
        self.lineEdit_6.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_17.addWidget(self.lineEdit_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_4.setMinimumSize(QtCore.QSize(300, 30))
        self.comboBox_4.setMaximumSize(QtCore.QSize(1000, 30))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_18)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        spacerItem7 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(86, 86, 86);\n"
"    color:  white;\n"
"    padding: 2px;\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_20.addWidget(self.pushButton_4)
        self.btn_save_2 = QtWidgets.QPushButton(self.widget_2)
        self.btn_save_2.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_save_2.setMaximumSize(QtCore.QSize(100, 30))
        self.btn_save_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 189, 0);\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-radius: 5px;\n"
"}")
        self.btn_save_2.setObjectName("btn_save_2")
        self.horizontalLayout_20.addWidget(self.btn_save_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.gridLayout.addWidget(self.main_menu, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.lineEdit_7.returnPressed.connect(self.loadUserData)
        self.btn_save_2.clicked.connect(self.UpdateData)

        self.retranslateUi(MainWindow)
        self.btn_expand.toggled['bool'].connect(self.icon_only_widget.setHidden) # type: ignore
        self.btn_expand.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.btn_logout_expanded.clicked.connect(MainWindow.close) # type: ignore
        self.btn_dashboard_expanded.toggled['bool'].connect(self.btn_dashboard_icon.setChecked) # type: ignore
        self.btn_user_expanded.toggled['bool'].connect(self.btn_user_icon.setChecked) # type: ignore
        self.btn_menu_expanded.toggled['bool'].connect(self.btn_menu_icon.setChecked) # type: ignore
        self.btn_dashboard_icon.toggled['bool'].connect(self.btn_dashboard_expanded.setChecked) # type: ignore
        self.btn_user_icon.toggled['bool'].connect(self.btn_user_expanded.setChecked) # type: ignore
        self.btn_menu_icon.toggled['bool'].connect(self.btn_menu_expanded.setChecked) # type: ignore
        self.btn_logout_icon.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def loadUserData(self):
        username = self.lineEdit_7.text()
        user = User()
        data = user.select_by_id(username)

        if data:
                self.lineEdit_4.setText(data[0])  # nama
                self.lineEdit_6.setText(data[2])  # password
                self.comboBox_4.setCurrentText(data[3])  # role
        else:
                QtWidgets.QMessageBox.warning(None, "Not Found", "User tidak ditemukan!")


    def UpdateData(self):
        username_baru = self.lineEdit7.text()
        nama_baru = self.lineEdit_4.text()
        password_baru = self.lineEdit_6.text()
        level_baru = self.comboBox_4.currentText()
        user_baru = User(username_baru,nama_baru, password_baru, level_baru)
        user_baru.update()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "NIBA"))
        self.label_5.setText(_translate("MainWindow", "RESTO"))
        self.btn_dashboard_expanded.setText(_translate("MainWindow", "Dashboard"))
        self.btn_user_expanded.setText(_translate("MainWindow", "User"))
        self.btn_menu_expanded.setText(_translate("MainWindow", "Menu"))
        self.btn_logout_expanded.setText(_translate("MainWindow", "Logout"))
        self.label_19.setText(_translate("MainWindow", "Ubah User"))
        self.label_21.setText(_translate("MainWindow", "Username"))
        self.label_14.setText(_translate("MainWindow", "Nama"))
        self.label_16.setText(_translate("MainWindow", "Password"))
        self.label_17.setText(_translate("MainWindow", "Role"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Admin"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Password"))
        self.pushButton_4.setText(_translate("MainWindow", "Kembali"))
        self.btn_save_2.setText(_translate("MainWindow", "Simpan"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
